name: CI/CD â€” Compose + Swarm

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout repo
        uses: actions/checkout@v5

      # 2) Login to Docker Hub
      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Build & push the Docker image
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            aadith27/mynginxapp:${{ github.sha }}
            aadith27/mynginxapp:latest

      # 4) SSH to EC2 and deploy
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Go to home
            cd /home/${{ secrets.EC2_USER }}

            # If existing folder then update, otherwise clone
            if [ -d "cicd_task" ]; then
              cd cicd_task
              git fetch --all
              git reset --hard origin/main
            else
              git clone https://github.com/Aadith-tech/cicd_task.git cicd_task
              cd cicd_task
            fi

            # Write the new tag to .env
            echo "IMAGE_TAG=${{ github.sha }}" > .env

            # Deploy the stack
            docker stack deploy -c docker-compose.yml my_stack
